[package]
name = "crow-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "crow"
path = "src/main.rs"

[dependencies]
crow-core = { path = "../crow-core" }
crow-utils = { path = "../crow-utils" }
anyhow = { workspace = true }
clap = { workspace = true }
rayon = { workspace = true }
once_cell = "1.21.3"
dialoguer = "0.12.0"
