use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CrowLockfile {
    pub version: u32,
    #[serde(rename = "package")]
    pub packages: Vec<LockedPackage>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dependencies: Vec<String>,
}

impl CrowLockfile {
    pub const VERSION: u32 = 1;

    pub fn new(packages: Vec<LockedPackage>) -> Self {
        Self {
            version: Self::VERSION,
            packages,
        }
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let body = toml::to_string(self)?;
        let content = format!(
            "# This file is automatically @generated by Crow.\n# It is not intended for manual editing.\n\n{}",
            body
        );
        fs::write(path, content)?;
        Ok(())
    }

    pub fn load(path: &Path) -> Result<Self> {
        let content = fs::read_to_string(path)?;
        let toml_content = content
            .lines()
            .filter(|line| !line.trim_start().starts_with('#'))
            .collect::<Vec<_>>()
            .join("\n");
        Ok(toml::from_str(&toml_content)?)
    }

    pub fn load_if_exists(path: &Path) -> Result<Option<Self>> {
        if path.exists() {
            Ok(Some(Self::load(path)?))
        } else {
            Ok(None)
        }
    }

    pub fn is_equivalent_to(&self, other: &Self) -> Result<bool> {
        Ok(toml::to_string(self)? == toml::to_string(other)?)
    }
}