use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CrowLockfile {
    pub version: u32,
    #[serde(rename = "package")]
    pub packages: Vec<LockedPackage>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dependencies: Vec<String>,
}

impl CrowLockfile {
    pub const VERSION: u32 = 4;

    pub fn new(packages: Vec<LockedPackage>) -> Self {
        Self {
            version: Self::VERSION,
            packages,
        }
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let body = toml::to_string(self)?;
        let content = format!(
            "# This file is automatically @generated by Crow.\n# It is not intended for manual editing.\n\n{}",
            body
        );
        fs::write(path, content)?;
        Ok(())
    }
}
