#[cfg(test)]
mod tests {
    use crow_core::lockfile::{CrowLockfile, LockedPackage};
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn crow_lockfile_new_version() {
        let lock = CrowLockfile::new(vec![]);
        assert_eq!(lock.version, CrowLockfile::VERSION);
        assert!(lock.packages.is_empty());
    }

    #[test]
    fn crow_lockfile_save_roundtrip() -> anyhow::Result<()> {
        let dir = tempdir()?;
        let path = dir.path().join("Crow.lock");
        let lock = CrowLockfile::new(vec![LockedPackage {
            name: "demo".to_string(),
            version: "1.0.0".to_string(),
            source: Some("git+https://example.com/x".to_string()),
            checksum: None,
            dependencies: vec!["other 0.2.0".to_string()],
        }]);
        lock.save(&path)?;
        let raw = fs::read_to_string(&path)?;
        assert!(raw.contains("generated by Crow"));
        assert!(raw.contains("demo"));
        Ok(())
    }
}
