[package]
name = "features_demo"
version = "0.1.0"
standard = "20"

# Пример зависимости из registry с фичами.
# features = ["json"] превращается в:
#   - флаг cmake: -DFMT_COMPONENTS=json
#   - линковка: -lfmt (имя пакета, так как libs не указаны явно)
[dependencies.fmt]
version = "^12"
features = ["json"]
